name: Build Workflow

permissions:
    contents: write

on:
    push
        #branches: master

jobs:
    build-mac:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.14
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Build with Pyinstaller
              run: |
                pyinstaller --clean main.spec 
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: Item_Creation-macos
                path: dist/main.app
            
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                name: Release ${{ github.ref_name }}
                generate_release_notes: false
            
            - name: Upload Release Asset
              id: upload-release-asset
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                files: |
                    dist/main.app
              